### ISSUE TITLE
Pool Hashrate is 0

### ISSUE THREAD

**Issue by Tifonous** [aionnetwork/aion_pool2#10]
The API reports pool api at 0. 
There have been a few cases where it displayed a hashrate, not necessarily correct but this happened only for a few minutes and around 3 times already.

I cannot find what is causing it and I have spent hours looking for the problem.
Could it be that the number of workers is small? Most of the time it is 1 or 2.

Here is what I get:
"poolStats": {
        "connectedMiners": 1,
        "poolHashrate": 0.0,
        "sharesPerSecond": 0
      },

However, everything else works fine:
      "networkStats": {
        "networkHashrate": 2252690.8479,
        "networkDifficulty": 0.0,
        "lastNetworkBlockTime": "2018-09-19T14:31:47.903017Z",
        "blockHeight": 1221005,
        "connectedPeers": 0
      },
      "topMiners": [
        {
          "miner": "0xa097d46bc137830a097498140d73acb2d03b02f351cfeda46add22dfc37ea2de",
          "hashrate": 366.80377313436179,
          "sharesPerSecond": 0.38417517222633518
        }

Specifically, the only miner right now has full hashrate stats for all hours connected. How exactly the miners get correct stats but the pool shows 0 hashrate?

**Comment by centrys-alin** [comment]
Hi,

The pool cannot detect your hashrate only as an estimations calculated something like network hashrate/speed of your pool finding blocks. If you don't find blocks for a long time, this number will be 0. As soon as you find a block, the calculation will be restarted.

**Comment by Tifonous** [comment]
This makes sense as I have been seeing spikes every time a block is generated.
Thank you
