### ISSUE TITLE
Kernel froze or not communicating with pool 

### ISSUE THREAD

**Issue by Knevil** [aionnetwork/aion_pool2#15]
We had an issue yesterday when one of our kernels simply froze up even though the server's resources are are fine. The same kernel later on that day simply stopped communicating with the pool. Restarting the kernel fixed the issue both times. I have attached the kernel logs.
[aion.log](https://github.com/aionnetwork/aion_pool2/files/2549855/aion.log)

**Comment by centrys-alin** [comment]
@Knevil,

This sounds like a kernel issue, most probably a deadlock in the code. I suggest to close this issue and open it here: https://github.com/aionnetwork/aion/issues, if this is still happening.

**Comment by equ1miner** [comment]
> @Knevil,
> 
> This sounds like a kernel issue, most probably a deadlock in the code. I suggest to close this issue and open it here: https://github.com/aionnetwork/aion/issues, if this is still happening.

Aion Java Kernel v0.3.2.1 fixed these known issues.
