### ISSUE TITLE
Shares not getting "Confirmed"

### ISSUE THREAD

**Issue by sbayegan** [aionnetwork/aion_pool2#17]
I've cloned this pool and have set it up on a Ubuntu 16.04 machine. The pool is connected to a Kernel and a miner is connected to it.

The miner is submitting shares that are getting accepted by the Daemon but are never confirmed and are not showing up on under the "Last Mined Blocks" on the pool's home page. 

When I log into the pool database and look at the blocks table, I see that the "status" of the most recent blocks is "pending" but "orphaned" for all of the other remaining blocks. None of the are confirmed.

Pool hashrate is also stuck at 0 and is not being updated, this is probably because no blocks have been properly mined yet as explained [here](https://github.com/aionnetwork/aion_pool2/issues/10)

No errors are logged by the mining pool either!

Does anyone know what is causing this problem?

**Comment by jzaluski** [comment]
What network are you connecting to? a private network?

based on the Status information, it sounds like the pool is not able to query the Kernel for block confirmations. Is the API on kernel configured with `net`?

Pool calculates hashrate based on how often it confirms blocks, so with no confirmation, there isn't any hashpower calculatioin. You can look at the individual miner hashrate.

**Comment by centrys-alin** [comment]
@sbayegan,

Any news on your side regarding this problem? It seems like a connection issue either from the pool side to the kernel, or from the kernel to other peers.

**Comment by sbayegan** [comment]
The issue was caused by account address discrepancies in the configurations
under the mining section. Thanks for following up.

**Comment by centrys-alin** [comment]
Thanks! Can you close this ticket?
