### ISSUE TITLE
Pool API not able to communicate with RPC server

### ISSUE THREAD

**Issue by suprnrdy** [aionnetwork/aion_pool2#2]
Kernel: 0.2.8
Pool: aion_pool2 Master Branch Commit on Jun 22, 2018

Issue:
Kernel is running, able to unlock wallet through web3 and able to receive RPC calls through curl such as: 
`curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":74}' http://127.0.0.1:8545`

This call results in a returned number of 16 connected peers.

When getting Pool API results, peerCount and networkDifficulty are zero: `curl http://127.0.0.1:4000/api/pools`

This also results in a failed payout to miners because pool is unable to unlock coinbase account.  Attempted to unlock through web3 and then do a payout with the same error:

```
System.Exception: Unable to unlock coinbase account for sending transaction
   at MiningCore.Blockchain.Aion.AionPayoutHandler.Payout(Balance balance)
```

**Comment by suprnrdy** [comment]
Reinstalled the kernel and started fresh.  Everything is working now.  Not sure why I was able to send curl commands to RPC, but the pool was not able to though.

**Comment by craziest** [comment]
Kernel: Aion v0.3.0 - Mainnet - Moldoveanu Peak
Pool: Master branch commit a214af4

I am having the same issue as already described. I am able to receive RPC calls by using curl and the result is a valid number.

When calling `curl http://127.0.0.1:4000/api/pools` on a completely fresh install (Ubuntu 16.04, kernel completely synced, pool software freshly built), this is the response:

`{
  "pools": [
    {
      "id": "aion1",
      "coin": {
        "type": "AION"
      },
      "ports": {
        "3333": {
          "listenAddress": "0.0.0.0",
          "difficulty": 1024.0,
          "varDiff": {
            "minDiff": 128.0,
            "maxDiff": 1E+24,
            "maxDelta": 500.0,
            "targetTime": 15.0,
            "retargetTime": 45.0,
            "variancePercent": 30.0
          }
        }
      },
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 1.0,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        },
        "keepTransactionFees": false,
        "minimumConfirmations": 30,
        "nrgFee": 0.0001,
        "minimumPeerCount": 1
      },
      "clientConnectionTimeout": 600,
      "jobRebroadcastTimeout": 10,
      "blockRefreshInterval": 400,
      "poolFeePercent": 0.75,
      "address": "0xa0c5da302ca0aa2d6ab5dc7cc7fe024f1b7f1902e7a8ebeb7ff0dd4b6da10a77",
      "poolStats": {
        "connectedMiners": 0,
        "poolHashrate": 0.0,
        "sharesPerSecond": 0
      },
      "networkStats": {
        "networkHashrate": 1252575.7653,
        "networkDifficulty": 0.0,
        "lastNetworkBlockTime": "2018-08-24T10:19:40.199501Z",
        "blockHeight": 1005923,
        "connectedPeers": 0
      },
      "topMiners": [],
      "totalPaid": 0.0
    }
  ]
}`

Reinstalling the kernel did not help. I even tried doing the same process on Ubuntu 18.04, same result. Network difficulty and peer count are empty when using the pool's api, but return a valid value through a RPC call.

Can someone please assist me, I would be very grateful. Thank you.
